import type { Metadata } from "next";
import Footer from "./components/footer";
import Header from "./components/header";
import "../app/globals.css"; // Make sure the path is correct

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en">
      <body className="">
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}
