import type { Metadata } from "next";
import "../globals.css"; // Make sure the path is correct
import Footer from "../components/footer";
import { ClerkProvider } from "@clerk/nextjs";
import Header from "../components/header";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body>
          <Header />
          {children}
          <Footer />
        </body>
      </html>
    </ClerkProvider>
  );
}
